spring.application.name=serene-weddings
spring.profiles.default=sqlserver
server.address=127.0.0.1
spring.jpa.open-in-view=false
spring.jackson.deserialization.fail-on-unknown-properties=true
server.error.include-message=never
